"""add stat_points to user

Revision ID: ad397a97d73c
Revises: ae9bd01d38b2
Create Date: 2026-01-09 00:03:41.262615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad397a97d73c'
down_revision = 'ae9bd01d38b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stat_points')

    # ### end Alembic commands ###
