"""Add xp and level to Bot

Revision ID: ae9bd01d38b2
Revises: 
Create Date: 2026-01-04 22:28:25.002744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9bd01d38b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        op.execute("ALTER TABLE bots ADD COLUMN IF NOT EXISTS xp INTEGER;")
        op.execute("ALTER TABLE bots ADD COLUMN IF NOT EXISTS level INTEGER;")
        return

    # SQLite / others: check columns before adding
    existing = set()
    result = bind.execute(sa.text("PRAGMA table_info(bots);"))
    for row in result:
        existing.add(row[1])

    with op.batch_alter_table("bots", schema=None) as batch_op:
        if "xp" not in existing:
            batch_op.add_column(sa.Column("xp", sa.Integer(), nullable=True))
        if "level" not in existing:
            batch_op.add_column(sa.Column("level", sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
