"""add botwins botlosses

Revision ID: b5e28b16b462
Revises: c383f3a5e51e
Create Date: 2026-01-29 16:14:05.128414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e28b16b462'
down_revision = 'c383f3a5e51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stat_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_points', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
