"""add email to user

Revision ID: c383f3a5e51e
Revises: ad397a97d73c
Create Date: 2026-01-17 00:17:32.852191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c383f3a5e51e'
down_revision = 'ad397a97d73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_effect', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('extra_attacks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ability_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('special_damage', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_energy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_proc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_defense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_clk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_luck', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_weapon_atk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot1_weapon_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bot2_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_energy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_proc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_defense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_clk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_luck', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_weapon_atk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bot2_weapon_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')
        batch_op.drop_column('rating')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('bot2_weapon_type')
        batch_op.drop_column('bot2_weapon_atk')
        batch_op.drop_column('bot2_luck')
        batch_op.drop_column('bot2_clk')
        batch_op.drop_column('bot2_defense')
        batch_op.drop_column('bot2_proc')
        batch_op.drop_column('bot2_energy')
        batch_op.drop_column('bot2_hp')
        batch_op.drop_column('bot1_weapon_type')
        batch_op.drop_column('bot1_weapon_atk')
        batch_op.drop_column('bot1_luck')
        batch_op.drop_column('bot1_clk')
        batch_op.drop_column('bot1_defense')
        batch_op.drop_column('bot1_proc')
        batch_op.drop_column('bot1_energy')
        batch_op.drop_column('bot1_hp')
        batch_op.drop_column('seed')

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('special_damage')
        batch_op.drop_column('ability_used')
        batch_op.drop_column('extra_attacks')
        batch_op.drop_column('special_effect')

    # ### end Alembic commands ###
